// src/components/LinkWidget.svelte
<script lang="ts">
	export let text: string = 'Link';
	export let href: string = '#';
	export let tab: 'new' | 'same' = 'same';

	// ! this needs a web scraper from the backend
	// function getFavicon() {
	// 	const linkTags = document.querySelectorAll("[rel='icon']");
	// 	const faviconRefs = linkTags.forEach((linkTag) => {
	// 		if (linkTag.getAttribute('href') !== null) {
	// 			return linkTag.getAttribute('href');
	// 		}
	// 	});

	// 	console.log(faviconRefs);
	// }
</script>

{#if tab === 'new'}
	<a
		{href}
		target="_blank"
		rel="noopener noreferrer"
		class="bg-teal-200 hover:bg-teal-300 text-black p-5 rounded-md">{text}</a
	>
{:else}
	<a {href} class="bg-teal-200 hover:bg-teal-300 text-black p-5 rounded-md">{text}</a>
{/if}

// src/components/LinkWidget/LinkWidget.tsx
import { linkIcon } from "~/utils/icons";

interface IProps {
  text: string;
  href: string;
  tab?: "new" | "same";
}

// ! this needs a web scraper from the backend
// function getFavicon() {
// 	const linkTags = document.querySelectorAll("[rel='icon']");
// 	const faviconRefs = linkTags.forEach((linkTag) => {
// 		if (linkTag.getAttribute('href') !== null) {
// 			return linkTag.getAttribute('href');
// 		}
// 	});
// <!-- todo: look in brave dev tools for how they do it

// 	console.log(faviconRefs);
// }

const LINK_CLASS =
  "bg-teal-200 hover:bg-teal-300 text-black p-5 rounded-md w-full h-20 flex justify-center items-center";

export default function LinkWidget(props: IProps) {
  return (
    <>
      <a
        href={props.href}
        target={props.tab === "same" ? "_self" : "_blank"}
        rel={props.tab === "same" ? "" : "noopener noreferrer"}
        className={LINK_CLASS}
      >
        {linkIcon}
      </a>
      <span className="w-full text-center text-sm">{props.text}</span>
    </>
  );
}
