// components/WidgetContainer/index.tsx
interface IProps {
  children: React.ReactNode;
  rowSpan: number;
  colSpan: number;
  rowStart: number;
  colStart: number;
  className?: string;
}
function WidgetContainer(props: IProps) {
  const gridClasses: string =
    `col-start-${props.colStart} ` +
    `row-start-${props.rowStart} ` +
    `col-span-${props.colSpan} ` +
    `row-span-${props.rowSpan}`;

  return (
    <div
      className={
        "h-full bg-plightgreen text-pdarkgreen flex justify-center py-10 px-2 rounded-md" +
        " " +
        gridClasses
      }
    >
      {props.children}
    </div>
  );
}

export default WidgetContainer;

// components/PageContent/WidgetContainer.vue
<template>
  <div
    class="h-full bg-plightgreen text-pdarkgreen flex justify-center py-10 px-2 rounded-md"
    :class="[
      getRowSpanClass,
      getColSpanClass,
      getRowStartClass,
      getColStartClass,
    ]"
  >
    <slot />
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

const WidgetContainer = defineComponent({
  props: {
    children: {
      type: String,
      default: "",
    },
    rowSpan: {
      type: Number,
      default: 1,
    },
    colSpan: {
      type: Number,
      default: 1,
    },
    rowStart: {
      type: Number,
      default: 1,
    },
    colStart: {
      type: Number,
      default: 1,
    },
  },
  computed: {
    getRowSpanClass() {
      return `row-span-${this.rowSpan}`;
    },
    getColSpanClass() {
      return `col-span-${this.colSpan}`;
    },
    getRowStartClass() {
      return `row-start-${this.rowStart}`;
    },
    getColStartClass() {
      return `col-start-${this.colStart}`;
    },
  },
});
export default WidgetContainer;
</script>
