// pages/index.vue
<script setup lang="ts">
import SiteWrapper from "../components/SiteStructure/SiteWrapper.vue";
import WidgetView from "../components/PageContent/WidgetView.vue";
import loadDataForWidget from "../utils/widget/load";
</script>

<template>
  <SiteWrapper>
    <div class="h-full">
      <WidgetView :widgetData="loadDataForWidget()"></WidgetView>
    </div>
  </SiteWrapper>
</template>

// pages/index.tsx
import { NextPage } from "next";
import SiteWrapper from "../components/SiteWrapper";
import WidgetView from "../components/WidgetView";
import loadDataForWidget from "../utils/widget/load";

const Home: NextPage = () => {
  return (
    <SiteWrapper>
      <div className="h-full">
        <WidgetView widgetData={loadDataForWidget()}></WidgetView>
      </div>
    </SiteWrapper>
  );
};

export default Home;
