// src/lib/WidgetContainer.svelte
<script lang="ts">
  export let rowSpan: number;
  export let colSpan: number;
  export let rowStart: number;
  export let colStart: number;

  const gridClasses: string = `col-start-${colStart} ` + `row-start-${rowStart} ` + `col-span-${colSpan} ` + `row-span-${rowSpan}`;
</script>

<div class={'h-full bg-plightgreen text-pdarkgreen flex justify-center items-center py-10 px-2 rounded-md' + ' ' + gridClasses}>
  <slot />
</div>

// components/WidgetContainer/index.tsx
interface IProps {
  children: React.ReactNode;
  rowSpan: number;
  colSpan: number;
  rowStart: number;
  colStart: number;
  className?: string;
}
function WidgetContainer(props: IProps) {
  const gridClasses: string = `col-start-${props.colStart} ` + `row-start-${props.rowStart} ` + `col-span-${props.colSpan} ` + `row-span-${props.rowSpan}`;

  return <div className={'h-full bg-plightgreen text-pdarkgreen flex justify-center items-center py-10 px-2 rounded-md' + ' ' + gridClasses}>{props.children}</div>;
}

export default WidgetContainer;
