// src/components/TimeWidget.svelte
<script lang="ts">
	let formatedDate: string;
	updateDate();

	setInterval(function () {
		updateDate();
	}, 1000);

	function updateDate() {
		formatedDate = Intl.DateTimeFormat('de-DE', {
			hour: 'numeric',
			minute: 'numeric'
		}).format(Date.now());
	}
</script>

<div class="text-6xl flex justify-center items-center">{formatedDate}</div>

// src/widgets/TimeWidget.tsx
import { useState } from "react";

export default function TimeWidget() {
  const [formatedTime, setFormatedTime] = useState<string>(
    Intl.DateTimeFormat("de-DE", {
      hour: "numeric",
      minute: "numeric",
    }).format(Date.now())
  );

  setInterval(function () {
    setFormatedTime(
      Intl.DateTimeFormat("de-DE", {
        hour: "numeric",
        minute: "numeric",
      }).format(Date.now())
    );
  }, 1000);

  return (
    <div className="text-6xl flex justify-center items-center">
      {formatedTime}
    </div>
  );
}
