// src/components/Toast.svelte
<script lang="ts">
	type ToastKind = 'error' | 'success' | 'info' | 'warning' | 'normal';
	type ToastColor =
		| { bg: 'bg-red-600'; text: 'text-white' }
		| { bg: 'bg-green-700'; text: 'text-white' }
		| { bg: 'bg-blue-600'; text: 'text-white' }
		| { bg: 'bg-yellow-500'; text: 'text-black' }
		| { bg: 'bg-gray-200'; text: 'text-black' };

	const toastMap: Record<ToastKind, ToastColor> = {
		error: { bg: 'bg-red-600', text: 'text-white' },
		success: { bg: 'bg-green-700', text: 'text-white' },
		info: { bg: 'bg-blue-600', text: 'text-white' },
		warning: { bg: 'bg-yellow-500', text: 'text-black' },
		normal: { bg: 'bg-gray-200', text: 'text-black' }
	};

	export let text = 'Error';
	export let kind: ToastKind = 'normal';
</script>

<div
	id=""
	class={`absolute bottom-16 bg-gray-200 text-black py-2 px-6 my-2 rounded-md ${toastMap[kind].bg} ${toastMap[kind].text}`}
>
	{text}
</div>

// web/src/components/Toast.tsx
import { useAtom } from "jotai";
import type { ToastColor, ToastType } from "~/lib/types/types";
import {
  checkedIcon,
  crossRoundIcon,
  infoIcon,
  warningIcon,
} from "~/lib/ui/icons";
import { toastTextAtom, toastTypeAtom } from "~/lib/ui/store";

export default function Toast() {
  const toastMap: Record<ToastType, ToastColor> = {
    error: { bg: "bg-red-600", text: "text-foreground" },
    success: { bg: "bg-green-700", text: "text-foreground" },
    info: { bg: "bg-foreground", text: "text-inverted" },
    warning: { bg: "bg-yellow-500", text: "text-inverted" },
  };

  const toastIconMap: Record<ToastType, JSX.Element> = {
    error: crossRoundIcon,
    success: checkedIcon,
    info: infoIcon,
    warning: warningIcon,
  };

  const [toastText] = useAtom(toastTextAtom);
  const [toastType] = useAtom(toastTypeAtom);

  const visibleClass = toastText.trim().length > 0 ? "visible" : "invisible";

  return (
    <div
      id=""
      className={`fixed bottom-16 my-2 flex items-center space-x-2 rounded-xl bg-foreground px-8 py-2 text-lg text-inverted shadow-xl ${visibleClass} 
      ${toastMap[toastType].bg} ${toastMap[toastType].text}`}
    >
      <span>{toastIconMap[toastType]}</span>
      <span>{toastText}</span>
    </div>
  );
}
